### ISSUE TITLE
Sector Splits and the Sector File/POF Update

### ISSUE THREAD

**Issue by bluenoseraviation** [stevenhperry/ZOBFacilities#81]
Currently, we are maintaining published splits by the sector file. The POF has been updated to reflect this.
[NL POF.zip](https://github.com/stevenhperry/ZOBFacilities/files/3752450/NL.POF.zip)
Sector file changes under sector titles
ZOB-64 to ZOB-04
ZOB-49 to ZOB-48 (119.87)

Other than that, all is well.
NL

**Comment by stevenhperry** [comment]
POF info picked up prior to Nov 2019 FNO.
Sector file updates remain.
